print remotes on checkout failure
Signed-off-by: Xida Ren <cedar.ren@gmail.com>

diff --git a/.github/workflows/bump_torch_mlir.yml b/.github/workflows/bump_torch_mlir.yml
--- a/.github/workflows/bump_torch_mlir.yml
+++ b/.github/workflows/bump_torch_mlir.yml
@@ -49,8 +49,8 @@ jobs:
         run: |
           cd third_party/torch-mlir
           git fetch origin
-          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-            git checkout ${{ github.event.inputs.bump_target }}
+          if [ "workflow_dispatch" == "workflow_dispatch" ]; then
+            git checkout upstream/main || { echo "Checkout failed. Available remotes:"; git remote -v; exit 1; }
           else
             git checkout origin/main
           fi
