Include which jobs failed in message

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1117,11 +1117,21 @@ jobs:
       # # Benchmark pipeline
       # - benchmarks
     steps:
-      - name: Getting combined job status
+      - name: Getting failed jobs
+        id: failed_jobs
         run: |
-          echo '${{ toJson(needs.*.result) }}' \
-            | jq --exit-status 'all(.=="success" or .=="skipped")' > /dev/null
-      - uses: sarisia/actions-status-discord@c193626e5ce172002b8161e116aa897de7ab5383 # v1.10.2
+          FAILING_JOBS="$(echo '${{ toJson(needs.*) }}' \
+            | jq --raw-output \
+            'map_values(select(.status!="success" and .status!="skipped")) | keys | join(",")' \
+          )"
+          echo "failed-jobs=${FAILING_JOBS}" >> $GITHUB_OUTPUT
+          if [[ "${FAILING_JOBS}" != "" ]]; then
+            echo "The following jobs failed: ${FAILING_JOBS}"
+            exit 1
+          fi
+      - name: Posting to Discord
+        uses: sarisia/actions-status-discord@c193626e5ce172002b8161e116aa897de7ab5383 # v1.10.2
         if: failure() && needs.setup.outputs.ci-stage == 'postsubmit'
         with:
           webhook: ${{ secrets.DISCORD_WEBHOOK }}
+          description: "The following jobs failed: ${{ steps.failed_jobs.failed_jobs }}"
