Add presubmit check for BUILD.bazel files (#13380)
This checks that we don't name any more files BUILD. Instead, all BUILD
files should be named BUILD.bazel.

Example failure of lint.sh:

![image](https://user-images.githubusercontent.com/10820234/236152658-a31a343b-1ad5-4844-8b1b-8e85bf5f9532.png)

Example failure of presubmit: 

![image](https://user-images.githubusercontent.com/10820234/236152773-20c41571-9e24-4fbb-979f-5a6bf0d17feb.png)

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -158,3 +158,16 @@ jobs:
           # pick up new files that have been added.
           git add -A
           git diff HEAD --exit-code
+
+  build_file_names:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checking out repository
+        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
+      - name: Check BUILD files are not named BUILD (prefer BUILD.bazel)
+        run: exit $(git ls-files '**/BUILD' | wc -l)
+      - name: Instructions for fixing the above linting error
+        if: ${{ failure() }}
+        run: |
+          echo "failure: found files named BUILD. Please rename the following files to BUILD.bazel:"
+          git ls-files '**/BUILD'
